### ISSUE TITLE
Issue building the lab documents

### ISSUE THREAD

**Issue by javiermarasco** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#12]
Hi, I was trying to build the lab documents and installing the pandoc version referenced in the build I got an error stating the --reference-docx parameter was deprecated, instead user --reference-doc

In the build script it's needed to change line #32 from:
pandoc $inputFile -o $outputFile --reference-docx=template.docx 

to: 

pandoc $inputFile -o $outputFile --reference-doc=template.docx 

After that change, all files were created successfully.

**Comment by polichtm** [comment]
appreciated - file updated
