### ISSUE TITLE
Suggestion on location for script "Set-10992P2SVPN.ps1"

### ISSUE THREAD

**Issue by javiermarasco** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#13]
In line 21, instead of using a $Location variable (that's not defined in the script) should be better to use $vnet.location to enforce the creation of the VNG in the same location as the VNET.

Thanks!

**Comment by polichtm** [comment]
Review Task 1 of Exercise 1 of the module 3 lab - you will notice that $location is set in step 5. 
Your suggestion is obviously still valid - but the lab should work as intended in the current form.
rgds
Marcin
