### ISSUE TITLE
Lab 3 error 'Legacy Cmak generation is not supported'

### ISSUE THREAD

**Issue by karlwest99** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#14]
In Lab 3, Exercise 3, Task 1, Step 1, when the referenced powershell cmd is run there occurs an error "...Operation returned an invalid status code 'BadRequest'....Legacy Cmak generation is not supported for gateway id <id>etc.etc..."

This has been repro'ed several times here despite using the Lab 3 LAK as seen currently in github for this course, and some research indicated it was because the AdatumVGateway is created with both 'Tunnel type' options of SSTP & IKEv2enabled.  

If (after receiving the error) one manually deselects the IKEv2 option for the AdatumVGateway from the Azure UI, and then re-runs the referenced cmd in step 1 it will now succeed.

Recommended to either add these manual steps to the instructions, or possibly instead modify the .ps1 setup script (Set-10992P2SVPN.ps1, I believe?) to explicitly create with only SSTP enabled.  

See also reference to similar/same problem described here (not referencing this course, but it is where we found the key info to getting things to work for this issue -- https://blogs.msdn.microsoft.com/wushuai/2017/12/10/integrate-web-app-with-azure-virtual-network-by-point-to-site-vpn/ )

**Comment by polichtm** [comment]
updated
