### ISSUE TITLE
'Unable to connect to Azure Site Recovery Services using the given settings'

### ISSUE THREAD

**Issue by karlwest99** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#15]
In Module 5, Exercise 2, Task 3, Step 8, an error is received (see attached pic) and one is unable to proceed.  While this was working when first tested roughly a year ago there appear to have been some changes in the meantime - likely within the behavior and/or options presented within Azure for the constructs required - that prevent success.  

The issue was reproduced multiple times using the Lab5 LAK within MLO, and also reproduced using a fresh 10992A course VM in a local lab.  While multiple attempts were made to identify precisely which option or options might be related, unfortunately a solution was not found.

![one](https://user-images.githubusercontent.com/31316994/34426266-6cf65614-ebe9-11e7-994b-875a76e6f781.png)

![two](https://user-images.githubusercontent.com/31316994/34426268-7163100c-ebe9-11e7-86cd-cd8a0b1d5590.png)

**Comment by polichtm** [comment]
Hi Karl,
I just stepped through this procedure and it worked for me as intended.
Can you confirm whether you enabled the Windows Update service on MIA-CL1?
Thnx
Marcin

**Comment by karlwest99** [comment]
Greetings,

Yes, I set the service to Manual as if one does not do that the install of
the .exe will fail at a point before getting to the error encountered.

In your repro, presumably you used the identical VM from the
currently-available 10992A course available from the download center?

When selecting options in Azure, did you select the 'Virtual networks' or
'Virtual networks (classic)' option?  (same question for the 'Storage
account' or 'Storage account (classic)' option?  At any point in running
through the instructions did you select *any* option that was not
specifically referenced in the github LAK?

Assuming this to be the case (I tested using various options above, just to
try and find a combination that would work for me) then perhaps there is a
networking/firewall issue common to our particular network, although it is
certainly odd that it is identical within the MLO labs, as well as our
general network.

In any case, I apologize - I certainly did not intend to have you do my
troubleshooting for me, but after a repro from a customer, 2 repros from
the support desk, and a series of repros on my end using both MLO &
local/fresh VM on different network i was fairly confident it was simply a
matter of an option within Azure that had changed.

Regards,
Karl

**Comment by polichtm** [comment]
Hi Karl, 
the intention is to use the Azure Resource Manager deployment model. I updated the lab steps to take into account changes to the Azure portal interface - let me know if there are any remaining steps that would require further clarification. 
I'm using my local lab with standard images. 
The error message seems to indicate a proxy-related issue - unfortunately without having more visibility into the environment where the issue you are describing surfaces, it is rather difficult to investigate the actual root cause. 
Do you happen to know whether the environments you are referring to are enforcing proxy-level restrictions? 

rgds
Marcin

**Comment by karlwest99** [comment]
Apologies for the false alarm - this does appear to be caused in our case
by an unexpected firewall/blocking rule!

**Comment by polichtm** [comment]
Hi Karl,
appreciate the follow-up. I'm glad that you managed to identify the root cause
rgds
Marcin
