### ISSUE TITLE
Azure Pass VM locations not allowed

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#16]
The **Create a Docker host in a Hyper-V virtual machine by using Docker Machine** step in both the **Lab_02** and **Lab_AK_02** (Lab B, Exercise 1) will fail if the student is using an **Azure Pass** subscription. Currently, only **EastUS** can be used to create **Standard_D1_V2** machines. 
Attached is a list of the VM sizes allowed for Azure Pass (as of December 21, 2017).
[VM_Sizes.xlsx](https://github.com/MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure/files/1600990/VM_Sizes.xlsx)

**Comment by polichtm** [comment]
updated to account for the VM size availability issues
