### ISSUE TITLE
Module 4 - Exercise 4 - Task 1 - Perform the restore

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#17]
The steps required to complete this task has completely changed and the lab need updating

The agent has been updated and instead of choosing files to restore and choosing the original or new location, the browse now opens file explorer and its a case of copying the hosts file and pasting it to the location you want to restore it to

**Comment by polichtm** [comment]
updated

**Comment by itbland** [comment]
@polichtm Thanks for the quick fix!
Suggestion: We _could_ leave the original steps mostly intact if we choose to recover the **Volume** instead of **individual files**. This would allow the option to replace or copy the **hosts** file, and minimize the changes to lab steps.

**Comment by polichtm** [comment]
you're welcome.
My intention was to maintain the current intent - i.e. back up and restore of a single file
