### ISSUE TITLE
Module 2 - Lab B - Exercise 2 - Task 3: Upload an image to the private Docker Registry

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#18]
When trying to push the image to the azure based registry with the command 

docker push localhost:5000/hello-world

It fails to copy and goes into a retry loop

If I create a local registry it works fine

Is there some step missing in the lab to, maybe, authenticate to the azure based registry?

The whole class had the same issue

**Comment by polichtm** [comment]
updated - pls use the updated procedure

**Comment by itbland** [comment]
@polichtm , when you corrected these steps, adding port 8080 to the nsg was left out.

**Comment by polichtm** [comment]
actually it's a bit easier to update docker machine command (--azure-open-port 8080 ) instead. Updated accordingly
thnx
Marcin

**Comment by itbland** [comment]
Do you ever sleep? 😉

That had just occurred to me and I was just looking that up (proper syntax to add a 2nd port)

Thanks!


________________________________

**Comment by polichtm** [comment]
;)
