### ISSUE TITLE
Visual Studio requires sign in to start - 10992A_LAB_AK_06.md

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#26]
I'm not sure if this is unique to my lab provider, but when VS is started in Ex 1, Task3, Step 1 it requires the student to either sign in or close the application. If this is the case for all labs, then this instruction from Step 6 should be added either to step 1, or a new step 2. (This also happens in an earlier lab.)

> If not, click Add an account, and then in the list, click Add an account. In the Sign in to your account window, type the name of the Microsoft account that is the Service Administrator or Co-Administrator of your Azure subscription, and then click Continue. In the Sign in to your account window, type in the password of the Microsoft account that you provided in the previous step, and then click Sign in.

**Comment by polichtm** [comment]
updated
