### ISSUE TITLE
Pandoc version confusion

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#41]
in the [10992B_GitHubUserGuideforMCTs](https://github.com/MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure/blob/master/10992B_GitHubUserGuideforMCTs.md), Pandoc 1.19.2 is specified. In the README in the [Build folder](https://github.com/MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure/tree/master/Build), Pandoc 1.13.2 is specified.  [Issue #68 in 20347A](https://github.com/MicrosoftLearning/20347-Enabling-and-Managing-Office365/issues/68) mentions that any Pandoc version other than 1.13.2 will result in conversion errors. Is it a "typo" in the 10992B_GitHubUserGuideforMCTs?

**Comment by polichtm** [comment]
updated
