### ISSUE TITLE
VM Names May need to be revised throughout the course

### ISSUE THREAD

**Issue by Michtian** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#44]
The vm names now come up with an error when deploying due to a name size limit: 

![badname](https://user-images.githubusercontent.com/24464234/39886852-540c9462-5456-11e8-8c93-498cc5fe975d.JPG)

**Comment by polichtm** [comment]
Hi Michtian,
Which lab/exercise/task/step and name are you referring to?
thnx
Marcin

**Comment by polichtm** [comment]
Hi Michtian,
I updated steps of the first module to account for this.
rgds
Marcin
