### ISSUE TITLE
 Mod 2, Lab B: Ex 1 PowerShell Module missing Error on Azure CLI command

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#45]
When running Module 2, Lab B: Moving containers between on-premises Hyper-V virtual machines and Azure virtual machines, Exercise 1: Creating a Docker host by using Docker Machine, Task 2 Create a Docker host in a Hyper-V virtual machine by using Docker Machine, Step 4.I'\ n the Administrator: Command Prompt window, type the following command, and then press Enter.

docker-machine create --driver hyperv --hyperv-virtual-switch "Microsoft Hyper-V Network Adapter - Virtual Switch" localdockervm

When the command is run, we are receiving a PowerShell Module not found error.  Cannot figure out how a Azure CLI can invoke a PowerShell error, and it doesn't state which PowerShell Module is missing.  Please advise.

Thanks, Dave Franklyn, MVP/MCT

**Comment by polichtm** [comment]
Dave,
Are you using the lab VM? The lab VM image includes all relevant Windows PowerShell modules
Thnx
Marcin

**Comment by davemct** [comment]
Yup.  LearnOnDemand vM for 10992B.  Everything launched from 10992B-MIA-CL1.  It is a Windows Server 2016 OS not Windows 10.  Is that correct?

I think the AzureRM PowerShell modules are loaded; don't know about the classic,,,

There appears to be--but I might be mistaken--a lot of changes to the Azure Pass Subscription as of Monday, Jun 21.  Think we should ask Merrick to check?  I tried to make a fifth S1_V3 VM and it said I exceeded my 10- core limit for the Azure pass.  THAT was a first for me in this environment.

Dave

**Comment by normandk** [comment]
I was getting that error 2 weeks ago.  Research showed it was actually an
issue with docker. (here is a link I found
https://github.com/docker/machine/issues/4424 )  I followed the suggestion
from that link from samirsyed and downloaded an older version of the
docker-machine.exe file and it solved the issue for me.

**Comment by itbland** [comment]
The fixed docker-machine.exe has been posted at: [https://github.com/docker/machine/releases/tag/v0.15.0](https://github.com/docker/machine/releases/tag/v0.15.0) but is not yet included in Docker CE for Windows (as of Friday 6/15/2018). After Docker CE is installed, download docker-machine-Windows-x86_64.exe from GitHub, unblock it and rename as docker-machine.exe and overwrite the existing copy in C:\Program Files\Docker\Docker\resources\bin

**Comment by polichtm** [comment]
updated instructions
