### ISSUE TITLE
Mod 06 Lab DSC error

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10992-IntegratingOn-PremisesInfrastructurewithMicrosoft-Azure#53]
I keep getting an error with the DSC for the VM in this lab (Fails to completely setup IIS) Is there a new DSC file for Windows Server 2016 Datacenter?

**Comment by itbland** [comment]
Let me look at this a little more, I may bring it back this evening...

**Comment by itbland** [comment]
Error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningTimeout\\\",\\r\\n \\\"message\\\": \\\"Provisioning of VM extension 'Microsoft.Powershell.DSC' has timed out. Extension installation may be taking too long, or extension status could not be obtained.\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by itbland** [comment]
[After GitHub's recent move to TLS 1.2, you can't onboard a VM to Azure Automation DSC using DIY Resource Manager templates](https://docs.microsoft.com/en-us/powershell/dsc/getting-started/azuredscexthistory#version-275)

**Comment by itbland** [comment]
I presume the error means that the .ps1 file should be digitally signed. The install seems to proceed (as long as the VM has >=2 vCPUs and >=4GB RAM), the deployment keeps running (seemingly forever) after the error and can be ignored.

**Comment by polichtm** [comment]
Lab 6 does not involve Azure Automation DSC.
Updated VM specs to account for the DSC extension
